config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Defines the root path route ("/")
  root to: 'pages#home'

  resources :groups do
    resources :group_members, only: %i[new create destroy]
    resources :santa_assignements, only: %i[new create]
  end

  resources :wishlists do
    resources :wishes
  end

  get '/profile', to: 'pages#profile', as: :profile

  resources :public_pages, only: %i[show index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_members, dependent: :destroy
  has_many :santa_assignements, dependent: :destroy
  has_many :user, through: :group_member
  belongs_to :admin, class_name: 'User'

  validates :name, presence: true, uniqueness: true
end

app/models/group_member.rb
class GroupMember < ApplicationRecord
  belongs_to :group
  belongs_to :user
  validates :group, :user, presence: { message: "Ce pseudo n'existe pas" }
  validates :user, uniqueness: { scope: :group, message: 'Cette personne est déja dans le groupe' }
end

app/models/santa_assignement.rb
class SantaAssignement < ApplicationRecord
  belongs_to :group
  belongs_to :giver, class_name: 'User', foreign_key: 'giver_id'
  belongs_to :receiver, class_name: 'User', foreign_key: 'receiver_id'
  validates :group, uniqueness: { scope: %i[giver receiver] }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :group_members, dependent: :destroy
  has_many :groups, through: :group_members
  has_many :given_assignements, class_name: 'SantaAssignement', foreign_key: 'giver_id', dependent: :destroy
  has_many :received_assignements, class_name: 'SantaAssignement', foreign_key: 'receiver_id', dependent: :destroy
  has_many :santa_assignements, through: :given_assignements, source: :giver, dependent: :destroy
  has_one_attached :avatar, dependent: :destroy
  has_one :wishlist, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true, uniqueness: { case_sensitive: false }

end

app/models/wish.rb
class Wish < ApplicationRecord
  belongs_to :wishlist
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  has_many :wishes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :home, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :home, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "Vous n'avez pas les autorisations pour faire ça."
  #   redirect_to(root_path)
  # end

  def autocomplete_user_nickname
    term = params[:term]
    items = User.where('nickname ILIKE ?', "%#{term}%").map(&:nickname)
    render json: items
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/group_members_controller.rb
class GroupMembersController < ApplicationController

  before_action :set_group, only: %i[new create destroy]
  before_action :verify_admin, only: %i[new create]

  def new
    @group_member = GroupMember.new
    authorize @group_member
  end

  def create
    @input = params[:group_member]
    @name = @input.values[0]
    @user = User.find_by('lower(nickname) = ?', @name.downcase)
    @group_member = GroupMember.new(group: @group, user: @user)
    if @group_member.save
      redirect_to new_group_group_member_path(@group)
    else
      render :new, status: :unprocessable_entity
    end
    authorize @group_member
  end

  def destroy
    @group_member = GroupMember.find(params[:id])
    @group_member.destroy
    redirect_to new_group_group_member_path(@group)
    authorize @group
    authorize @group_member
  end

  private

  def params_group_member
    params.require(:group_member).permit(:group, :user)
  end

  def set_group
    @group = Group.find(params[:group_id])
    authorize @group
  end

  def verify_admin
    redirect_to root_path unless @group.admin == current_user
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  def index
    @user = current_user
    @groups = policy_scope(Group)
  end

  def show
    @members = @group.group_members.map(&:user)
    @santa_assignement = SantaAssignement.where(group: Group.find(params[:id]), giver_id: current_user)[0]
    unless @santa_assignement.nil?
      @receiver = User.find(@santa_assignement.receiver_id)
    end
  end

  def new
    @group = Group.new
    authorize @group
  end

  def create
    @group = Group.new(params_group)
    @user = current_user
    @group.admin = @user
    @group_member = GroupMember.new(group: @group, user: @user)
    if @group.save!
      @group_member.save!
      redirect_to new_group_group_member_path(@group)
    else
      render :new, status: :unprocessable_entity, notice: "Nouveau groupe créé"
    end
    authorize @group
    authorize @group_member
  end

  def edit
  end

  def update
    @group.update(params_group)
    redirect_to group_path(@group)
  end

  def destroy
    @group.destroy
    redirect_to profile_path
  end

  private

  def params_group
    params.require(:group).permit(:name, :admin)
  end

  def params_group_member
    params.require(:group_member).permit(:group, :user)
  end

  def set_group
    @group = Group.find(params[:id])
    authorize @group
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def profile
    @wish = Wish.new
    @wishlist = current_user.wishlist
  end

end

app/controllers/public_pages_controller.rb
class PublicPagesController < ApplicationController

  def index
    @users = policy_scope(User)
    if params[:query].present?
      @users = @users.where("nickname ILIKE ?", "%#{params[:query]}%")
    end
    authorize @users
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end
end

app/controllers/santa_assignements_controller.rb
class SantaAssignementsController < ApplicationController
  before_action :set_group, :set_group_members, only: %i[new destroy]

  def new
    santas = @group_members.map do |group_member|
      group_member.user
    end
    index = 0
    (santas.size - 1).times do
      SantaAssignement.create!(group: @group, giver: santas[index], receiver: santas[index + 1])
      index += 1
    end
    SantaAssignement.create!(group: @group, giver: santas[-1], receiver: santas[0])
    @santa_assignements = @group.santa_assignements
  end

  private

  def params_group_member
    params.require(:santa_assignement).permit(:group, :giver, :receiver)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  def set_group_members
    @group_members = @group.group_members.shuffle
  end
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  before_action :set_wish, only: %i[edit update destroy]

  def new
    @wish = Wish.new
    authorize @wish
  end

  def create
    @wish = Wish.new(params_wish)
    @wish.wishlist = current_user.wishlist
    if @wish.save!
      redirect_to profile_path
    else
      render :profile, status: :unprocessable_entity
    end
    authorize @wish
  end

  def edit
  end

  def update
    @wish.update(params_wish)
    redirect_to profile_path
    authorize @wish
  end

  def destroy
    @wish.destroy
    redirect_to profile_path
    authorize @wish
  end

  private
  def set_wish
    @wish = Wish.find(params[:id])
  end

  def params_wish
    params.require(:wish).permit(:content, :wishlist)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_members_helper.rb
module GroupMembersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/public_pages_helper.rb
module PublicPagesHelper
end

app/helpers/santa_assignements_helper.rb
module SantaAssignementsHelper
end

app/views/group_members/new.html.erb
<div class="form-container">
  <%= simple_form_for [@group, @group_member] do |f| %>
  <%= f.input :user, prompt: "Choisir par pseudo",
      label: "Personne à ajouter",
      input_html: { autocomplete: 'off' } %>

  <%= f.submit "Ajouter",
      class: "btn btn-green" %>

  <% end %>
  <h2>
    <%= @group.name %>
  </h2>
  <div class="row">
    <div class='col-xl-4 col-md-6'>
  <ul >
  <% @group.group_members.each do |group_member| %>
    <li>
    <%= group_member.user.nickname %>
    <%= link_to "X", group_group_member_path(@group, group_member), data: { turbo_method: "DELETE", turbo_confirm: "Es-tu sûr(e) de vouloir supprimer cette personne du groupe ?"}, class:"" %>
    </li>

  <% end %>
  </ul>


    </div>
  </div>

  <%= link_to "Enregistrer le groupe", group_path(@group), class: "btn btn-green" %>

</div>

app/views/groups/edit.html.erb
<div class="form-container">
  <%= simple_form_for [@group] do |f| %>
    <%= f.input :name,
    label: 'Renommer le groupe',
    class: "test"%>
        <%= f.submit "Nouveau nom" ,
        class: "btn btn-green"%>
  <% end %>
</div>

app/views/groups/index.html.erb
<h1>Mes groupes</h1>

<% @groups.each do |group| %>
  <%= link_to group_path(group) do %>
  <%= group.name %>
  <% end %>
<% end %>

app/views/groups/new.html.erb
<div class="form-container">
  <h1>Créer un nouveau groupe</h1>
  <%= simple_form_for [@group] do |f| %>
    <%= f.input :name,
        label: "Nom du groupe",
        input_html: { autocomplete: 'off' }%>
        <%= f.submit "Nouveau groupe",
        class: "btn btn-green" %>
  <% end %>
</div>

app/views/groups/show.html.erb
<div class="d-flex container-sp-btw  group-show">


<div class="titre-admin">
  <h1><%= @group.name %></h1>
  <% if current_user != @group.admin %>
  <p>Groupe géré par <%= @group.admin.nickname %></p>
  <% end %>
  <div class="modif-group">
    <% if policy(@group).edit? %>
    <%= link_to"renommer le groupe", edit_group_path(@group), class:"edit-group"%>
    <% end %>
    <% if @group.admin == current_user %>
    <%= link_to"supprimer le groupe", group_path(@group), data: { turbo_method: "DELETE", turbo_confirm: "Es-tu sûr(e) de vouloir supprimer ce groupe ?"}, class:"edit-group"  %>
    <% end %>
  </div>
</div>

<div class="group-members">
  <h1>Membres</h1>
   <% if @group.admin == current_user %>
      <% unless @receiver %>
        <%= link_to "Modifier les membres du groupe", new_group_group_member_path(@group), class:"edit-group" %>
      <% end %>
   <% end %>
  <ul>
  <% @members.each do |member| %>
    <% if member != current_user %>
      <%= link_to  public_page_path(member) do %>
        <li><%= member.nickname %></li>
      <% end %>
    <% end %>
  <% end %>
  </ul>
</div>

<div class="infos-group">
  <div class="tirage">
    <% unless @receiver %>
      <% if @group.admin == current_user %>
      <%= link_to new_group_santa_assignement_path(@group),  data: { turbo_method: "GET", turbo_confirm: "As-tu bien ajouté tout le monde au groupe ? Une fois le tirage au sort effectué il n'est plus modifiable !"}, class:"" do %>
        <h1>Faire le tirage au sort</h1>
        <% end %>
      <% end %>
    <% end %>
    <% if @receiver %>
  <p>Tu es le secret Santa de</p>
  <%= link_to @receiver.nickname, public_page_path(@receiver)%>
  <% end %>

  </div>


</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecretSanta</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@300;400;500;600;700&family=Source+Sans+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700;1,900&display=swap" rel="stylesheet">

  </head>

  <body>
    <% unless action_name == "home" %>
      <div class="banner-site">
      <%= render 'shared/navbar' %>
      <div class="container">
    <% end %>

    <%= yield %>

    <%= render "shared/flashes" %>
    <% unless action_name == "home" %>
      </div>
     </div>
     <%= render 'shared/footer' %>
    <% end %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">

  <%= render 'shared/navbar' %>


  <div class="container">
    <br>
    <h1>Organisez des soirée Secret Santa entre amis et en famille !</h1>
    <p>Créez des groupes de participants et lancer le tirage au sort<p>
    <p>En manque d'inspiration ? Allez voir les Wish Lists de vos amis<p>
    <%= link_to new_group_path, class: 'btn btn-green' do %>
      Créez un nouveau groupe
    <% end %>
  </div>
   </div>
   <%= render 'shared/footer' %>

app/views/pages/profile.html.erb
<div class="d-flex container-sp-btw ">
  <div class="avatar-profile">
    <%= cl_image_tag(current_user.avatar.key, width: 200, height: 200, crop: :fill) %>
    <p>Modifier photo</p>
  </div>

<div class="card card-profile">
  <div class="group member">
    <div>
      <h2>
        Mes groupes
      </h2>
      <ul>
        <% current_user.groups.each do |group| %>
          <%= link_to group_path(group) do%>
          <li >
            <p>
            <%= group.name %>
            </p>
          </li>
          <% end %>
        <% end %>
      </ul>
    </div>
    <%= link_to "Créer un goupe", new_group_path, class: "a-profile btn btn-green"%>
  </div>
</div>

<div class="card card-profile">
  <div class="group">
    <div>
      <h2>Ma wishlist</h2>
      <ul>
        <% current_user.wishlist.wishes.each do |wish| %>

          <li data-controller="edit">
            <div class="wish d-flex" data-wish-id="<%= wish.id %>">

              <p id="wish-content" data-edit-target="wish" data-value-edit="<%= wish.content %>">
                <%= wish.content %>
              </p>

              <div id="wish-edit" class="d-none" data-edit-target="formedit" >
                <%= simple_form_for [@wishlist, wish] do |f| %>
                <%= f.input :content, class: "form-control area", label: false %>
                <%= f.submit "Modifier", class: "submit-button" %>
                <% end %>
              </div>

              <div class="wish-icon" data-edit-target="icon">
                <i class="fa-solid fa-pen edit-wish" data-action="click->edit#toggledisplay"></i>
                <%= link_to  wishlist_wish_path(@wishlist, wish), data: {turbo_method: "DELETE"}, class:"" do %>
                  <i class="fa-solid fa-xmark edit-wish"></i>
                <% end %>
              </div>
          </div>
        </li>
        <% end %>
      </ul>
    </div>

    <div class="form-wish">
      <%= simple_form_for [@wishlist, @wish], html: { class: 'form-inline' } do |f| %>
      <%= f.input :content, label: false, input_html: { autocomplete: 'off' }  %>
      <%= f.submit "Ajouter", class:"submit"  %>
      <% end %>
    </div>

  </div>
</div>

</div>

app/views/public_pages/index.html.erb
<div class="container public">
  <ul>
    <% @users.each do |user|%>
      <li>
        <%= link_to public_page_path(user) do%>
          <%= user.nickname %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/public_pages/show.html.erb
<div class="d-flex container-sp-ar public-profile">
  <div class="avatar-profile">
    <%= cl_image_tag(@user.avatar.key, width: 200, height: 200, crop: :fill) %>
    <h1>
      <%= @user.nickname %>
    </h1>
  </div>

  <div class="card card-public">
    <div class="group-public">
      <h1>Wishlist</h1>
      <ul>
      <% @user.wishlist.wishes.each do |wish| %>
        <li><p><%= wish.content %></p></li>
      <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer" id="footer" <%= "footer-home" if action_name == "home" %>>
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    <p>SecretSanta Inc. 68 Ave Parmentier 75011 Paris </p><i class="fa-regular fa-flux-capacitor"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon ">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <h1 class="mb-0 mt-2">SECRET</h1>
      <h1 class="mt-0">SANTA</H1>
    <% end %>

           <div class="nav-center">

            <div class="doodle-border search-bar">
              <%= form_with url: public_pages_path, method: :get, html: { data: { search_items_target: 'form' } } do |f| %>
                <%= f.text_field :query,
                                  id: "navi-search",
                                  placeholder: 'Qui cherchez-vous ?',
                                  value: params[:query],
                                  data: {
                                  search_items_target: 'searchInput',
                                  action: "keyup->search-items#update"
                                  } %>
                <%= submit_tag "Chercher" , class: "d-none" %>
              <% end %>
            </div>
        </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
             <% if current_user.avatar.attached? %>
              <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "basic_profil", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <%end%>
             <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", profile_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>